name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  dio:
  image_picker: ^1.2.1
  cryptography: ^2.9.0

  camera: ^0.11.3
  flutter_bloc: ^9.1.1
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  path: ^1.9.1
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/2e93nw8.jpg
  uses-material-design: true
