name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.6
  image_picker: ^1.2.1
  cryptography: ^2.9.0

  camera: ^0.11.3
  flutter_bloc: ^9.1.1
  connectivity_plus: ^7.0.0
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/2e93nw8.jpg
  uses-material-design: true
